#!/bin/bash
#SBATCH -J 0job
#SBATCH -A ACF-UTK0035
#SBATCH --partition=campus
#SBATCH --qos=campus
#SBATCH --nodes=1
##SBATCH --ntasks-per-node=48
#SBATCH --ntasks=16
##SBATCH --nodelist=clr1144
#SBATCH --time=24:00:00
##SBATCH -e Demonstration.e%j
##SBATCH -o Demonstration.o%j
echo $SLURM_JOB_NODELIST
echo $SLURM_NTASKS

export OMP_NUM_THREADS=1

cd $SLURM_SUBMIT_DIR
module purge
module load anaconda3
source $ANACONDA3_SH
conda activate /lustre/isaac24/scratch/tliang7/myVenvs/myvenv/

srun -n 16 python application.py